language: java
deploy:
  provider: releases
  api_key:
    secure: b9tqE71CEatDDOtTa5UcWgVmCUenOAhZ6X7ajzxHuHu9UhxBcBe+J82j+V5DVhgeRCS35vHfkqhz1R1boWb0FEgAV09YuseFAFzyhAI9OJI6E+iJf5kbR6t7z2j4DlqSpf3w8qCus8345Pv/Repq+kHxqe1jIuVgSJxPwEcybaGROy2UDt3VA8ZQQy0mcPWbPZkhL4t3mM0u0ianJS/tCgBG7mCjQF4louuv9rd0OMG1ApIT5ydYT+V8GKwYdEWTAj2wuiPIZXCJZ6V3L5FuVqcu3zwiylJ7o4seO7qtt4QbYQwI0CwaypvFJ1UEO48LionbzxPLU3LIeF2S/ktSqJ7aZb2us1AaEyndm4Ce8URFgrWfoKP6+5z5cg0DgPK0lXg75JrdBVHVuAywhCweBqmNYeft6Reh2mLVof9nNj9hfe1pIsJ8KAlbT/FHBqfEEi24vwr7PAPEpXAaupbrCkRf+TqBAWmJxUe7xAQaux9f9I0tE3N8ZxzisFVDcUNhNl1wwYKp2F+vR8VnXgMtIzdjOFnM2HJxA5RBA6r2oDu+szZSo92nx7u385m4abJl3jrRuVRYSKU7Fc2SMr++D3Sdy7rYL756Hg9CjxqeJ75KzyDCeOvwSYfDKWy9WruzJYzWACpj5tE8MzPJMrwPSAfTHZdycphBLqGAk6RUFiY=
  file: build/distributions/xld-kubernetes-gke-plugin-6.2.3.xldp
  on:
    repo: xebialabs-community/xld-kubernetes-gke-plugin
    all_branches: true
    tags: true
notifications:
  hipchat:
    rooms:
      secure: RuVtkD4RbS6M/FvjSEY6isHaCQbQx6oCT6LcGEJqp1C05Auxnq2rras8DsUhm07z1zlvR5Yhy1XCNHplRxIPS51Fct1G1IUyfLxihfX5CCYfZk2k7x35aqRpPm88SThwzpBQDUCQBzCDG9SsbjkfonGBs5UILYpoImz6rx6lANtdAkWzhLZ8VTpLvKf8UY1qfbRK0qG91CAl6BG0vh5zL9W6zgNO0eVPSFEBFrnzoJs5Vl8Nxx5myYCLllCI1ljfpjbLJTSYEeX6yXQS4kCQsKbLSM8f3FL+1IJ9l3JCDrFpkvKtoNCXBvJdmk/NYjDATDSRyu1+ZvZDm675P9pa5hNH0vz36qS1NqvYDIeIzw6rpvVCBDN/0ytMoIJNEmjX/qvvpDWluE0GMiOCZr8z2Z4fR1P7WSO1alTZ2qEc7tGhLcuYdvUEBLWozJGyUDEQcDuQ8dWcS28lHBWMUMa4z6gZ/W4SLPV6aAbH7qXOwcWgYwnmH3g8pVjhvzMRVMj7ZIzFVnwEOMeqvmT729M7UomWvzRXQuVXEnHtBRKt6XE07WVtosNO4vIHeSHy1x5Mj+RtG/TOZ/31fE7Q/uOFPGpED4JoCg51gkBwLqCzRBrNjUDkcHDNaIZDAr3RWQBVPJd+UQlkfQQbrDt0Y41neiy7iFGzSoQrpfAhf1hvehM=
